import React from "react";
import {useEffect,useState} from "react";import api from "../services/api";import {Users,Target,Mail,Send,MessageCircle,TrendingUp,ArrowUpRight} from "lucide-react";import StatCard from "../components/StatCard";import {Link} from "react-router-dom";
export default function Dashboard(){const [data,setData]=useState(null);useEffect(()=>{api.get("/analytics/dashboard").then(r=>setData(r.data))},[]);
 if(!data)return <div className="text-slate-500">Loading dashboard…</div>;const k=data.kpis;
 return <div><div className="flex items-end justify-between"><div><div className="text-accent text-xs uppercase tracking-widest">Overview</div><h1 className="text-3xl font-semibold mt-1">Lead intelligence</h1><p className="text-sm text-slate-500 mt-2">Your opportunity pipeline at a glance.</p></div><Link to="/leads" className="px-4 py-2 rounded-xl bg-white text-ink text-sm font-semibold">View Leads</Link></div>
 <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-7">{[[Users,"Total Leads",k.totalLeads,"All discovered opportunities"],[Target,"High Intent",k.highIntent,"Strong business signals"],[Mail,"Emails Generated",k.generated,"AI-assisted drafts"],[Send,"Emails Sent",k.sent,"Approved and sent"]].map(([i,l,v,s])=><StatCard key={l} icon={i} label={l} value={v} sub={s}/>)}</div>
 <div className="grid md:grid-cols-3 gap-4 mt-4"><StatCard icon={MessageCircle} label="Replies" value={k.replies} sub={`${k.replyRate}% reply rate`}/><StatCard icon={TrendingUp} label="Qualified Leads" value={k.qualified} sub={`${k.conversionRate}% conversion from sends`}/><StatCard icon={ArrowUpRight} label="New Leads (7d)" value={k.newLeads} sub="Recent discovery activity"/></div>
 <div className="grid lg:grid-cols-2 gap-4 mt-6"><div className="glass rounded-2xl p-5"><h3 className="font-semibold">Lead sources</h3><div className="mt-5 space-y-3">{data.bySource.map(x=><div key={x._id} className="flex justify-between text-sm"><span className="text-slate-400">{x._id}</span><span>{x.value}</span></div>)}</div></div><div className="glass rounded-2xl p-5"><h3 className="font-semibold">Matched services</h3><div className="mt-5 space-y-3">{data.byService.slice(0,7).map(x=><div key={x._id} className="flex justify-between text-sm"><span className="text-slate-400">{x._id}</span><span>{x.value}</span></div>)}</div></div></div>
 </div>
}
