import React from "react";
import {Link} from "react-router-dom";
import {ArrowRight,ShieldCheck,Sparkles,Target,Mail,BarChart3,Globe2,BrainCircuit} from "lucide-react";
const services=["Web Development","Cloud Solutions","Data Engineering","AI & Machine Learning","3D Design","Frontend Development","Backend Development"];
export default function Landing(){
 return <div className="min-h-screen">
  <nav className="max-w-7xl mx-auto px-6 py-5 flex items-center justify-between"><div className="font-bold text-lg flex items-center gap-2"><span className="h-8 w-8 rounded-lg bg-gradient-to-br from-accent to-cyan grid place-items-center"><Sparkles size={16}/></span>Kognitribe</div><div className="flex gap-3"><Link to="/login" className="px-4 py-2 text-sm text-slate-300">Login</Link><Link to="/register" className="px-4 py-2 rounded-xl bg-white text-ink text-sm font-semibold">Get Started</Link></div></nav>
  <section className="max-w-7xl mx-auto px-6 pt-20 pb-24 grid lg:grid-cols-2 gap-14 items-center"><div><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-accent/10 border border-accent/20 text-accent text-xs"><Sparkles size={13}/> AI-assisted lead intelligence</div><h1 className="mt-6 text-5xl md:text-7xl font-semibold tracking-tight leading-[1.02]">Find the right opportunities.<span className="text-transparent bg-clip-text bg-gradient-to-r from-accent to-cyan"> Reach out intelligently.</span></h1><p className="mt-6 text-lg text-slate-400 max-w-xl">Discover relevant public business opportunities, qualify them with AI, personalize outreach and keep a human in control of every send.</p><div className="mt-8 flex gap-3"><Link to="/register" className="px-5 py-3 rounded-xl bg-accent font-semibold flex items-center gap-2">Get Started <ArrowRight size={18}/></Link><Link to="/login" className="px-5 py-3 rounded-xl border border-white/10">Login</Link></div><div className="mt-7 flex items-center gap-5 text-xs text-slate-500"><span className="flex gap-2 items-center"><ShieldCheck size={15}/> Responsible outreach</span><span className="flex gap-2 items-center"><Target size={15}/> Quality over quantity</span></div></div>
   <div className="glass rounded-3xl p-5 shadow-2xl"><div className="text-xs text-slate-500 mb-4">LEAD INTELLIGENCE PREVIEW</div><div className="grid grid-cols-2 gap-3">{[["Total Leads","1,284"],["High Intent","246"],["Emails Approved","184"],["Reply Rate","12.8%"]].map(x=><div className="bg-white/[.03] rounded-2xl p-4" key={x[0]}><div className="text-xs text-slate-500">{x[0]}</div><div className="text-2xl font-semibold mt-2">{x[1]}</div></div>)}</div><div className="mt-4 p-4 rounded-2xl bg-white/[.03]"><div className="flex items-center justify-between"><div><div className="text-sm font-medium">React + Node.js requirement</div><div className="text-xs text-slate-500 mt-1">Public opportunity • Reddit</div></div><div className="text-cyan font-semibold">88/100</div></div><div className="mt-4 h-2 rounded-full bg-slate-800"><div className="h-2 rounded-full bg-gradient-to-r from-accent to-cyan w-[88%]"/></div><div className="mt-4 flex gap-2 flex-wrap"><span className="text-[11px] px-2 py-1 rounded-lg bg-accent/10 text-accent">Frontend</span><span className="text-[11px] px-2 py-1 rounded-lg bg-accent/10 text-accent">Backend</span><span className="text-[11px] px-2 py-1 rounded-lg bg-accent/10 text-accent">Web Development</span></div></div></div>
  </section>
  <section className="max-w-7xl mx-auto px-6 py-20"><div className="grid md:grid-cols-3 gap-5">{[[Globe2,"Legitimate sources","RSS, public APIs and authorized source integrations."],[BrainCircuit,"AI qualification","Analyze intent, score opportunities and match services."],[Mail,"Human-approved outreach","Every AI email is reviewed before it can be sent."]].map(([I,t,d])=><div className="glass rounded-2xl p-6" key={t}><I className="text-accent"/><h3 className="mt-5 font-semibold">{t}</h3><p className="mt-2 text-sm text-slate-400">{d}</p></div>)}</div></section>
  <section className="max-w-7xl mx-auto px-6 py-20 border-t border-white/10"><div className="flex items-end justify-between gap-4"><div><div className="text-accent text-xs uppercase tracking-widest">Capabilities</div><h2 className="mt-2 text-3xl font-semibold">Kognitribe services</h2></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-8">{services.map((s,i)=><div className="glass rounded-2xl p-5" key={s}><div className="text-accent text-xs">0{i+1}</div><h3 className="mt-5 font-semibold">{s}</h3><p className="text-sm text-slate-500 mt-2">Configurable service capability for AI matching.</p></div>)}</div></section>
  <footer className="border-t border-white/10 py-8 text-center text-xs text-slate-600">Kognitribe Global Solutions • AI-assisted lead discovery and personalized B2B outreach</footer>
 </div>
}
