import React from "react";
import {useEffect,useState} from "react";import api from "../services/api";import {Save,ShieldCheck} from "lucide-react";
export default function Settings(){const [tab,setTab]=useState("company"),[company,setCompany]=useState(null),[ai,setAi]=useState(null),[users,setUsers]=useState([]),[msg,setMsg]=useState("");
 const load=async()=>{const [c,a]=await Promise.all([api.get("/settings/company"),api.get("/settings/ai")]);setCompany(c.data);setAi(a.data);try{setUsers((await api.get("/settings/users")).data)}catch{} };useEffect(()=>{load()},[]);
 const saveCompany=async()=>{await api.put("/settings/company",company);setMsg("Company settings saved")};const saveAI=async()=>{await api.put("/settings/ai",ai);setMsg("AI settings saved")};
 if(!company||!ai)return <div>Loading settings…</div>;
 return <div><div className="text-accent text-xs uppercase tracking-widest">Configuration</div><h1 className="text-3xl font-semibold mt-1">Settings</h1><div className="flex gap-2 mt-6 overflow-auto">{["company","ai","email","users","compliance"].map(t=><button key={t} onClick={()=>setTab(t)} className={`px-4 py-2 rounded-xl text-sm whitespace-nowrap ${tab===t?"bg-accent":"bg-white/5 text-slate-400"}`}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{msg&&<div className="mt-4 text-sm text-cyan">{msg}</div>}
 {tab==="company"&&<div className="glass rounded-2xl p-6 mt-4 max-w-3xl"><label className="text-sm">Company name<input className="field" value={company.companyName||""} onChange={e=>setCompany({...company,companyName:e.target.value})}/></label><label className="block text-sm mt-4">Description<textarea className="field" rows="4" value={company.description||""} onChange={e=>setCompany({...company,description:e.target.value})}/></label><div className="grid md:grid-cols-2 gap-4 mt-4"><label className="text-sm">Website<input className="field" value={company.website||""} onChange={e=>setCompany({...company,website:e.target.value})}/></label><label className="text-sm">Contact email<input className="field" value={company.contactEmail||""} onChange={e=>setCompany({...company,contactEmail:e.target.value})}/></label></div><label className="block text-sm mt-4">Email signature<textarea className="field" rows="3" value={company.emailSignature||""} onChange={e=>setCompany({...company,emailSignature:e.target.value})}/></label><button onClick={saveCompany} className="mt-5 px-4 py-2 rounded-xl bg-accent flex gap-2"><Save size={16}/> Save</button></div>}
 {tab==="ai"&&<div className="glass rounded-2xl p-6 mt-4 max-w-3xl"><div className="text-sm text-slate-400 mb-5">AI provider credentials should preferably be stored in server environment variables. This UI supports provider configuration for admin-managed deployments.</div><label className="text-sm">Provider<input className="field" value={ai.provider||""} onChange={e=>setAi({...ai,provider:e.target.value})}/></label><div className="grid md:grid-cols-2 gap-4 mt-4"><label className="text-sm">Model<input className="field" value={ai.model||""} onChange={e=>setAi({...ai,model:e.target.value})}/></label><label className="text-sm">Base URL<input className="field" value={ai.baseUrl||""} onChange={e=>setAi({...ai,baseUrl:e.target.value})}/></label></div><label className="block text-sm mt-4">API key<input className="field" type="password" value={ai.apiKey||""} placeholder="Leave masked value unchanged" onChange={e=>setAi({...ai,apiKey:e.target.value})}/></label><label className="block text-sm mt-4">System prompt<textarea className="field" rows="5" value={ai.systemPrompt||""} onChange={e=>setAi({...ai,systemPrompt:e.target.value})}/></label><button onClick={saveAI} className="mt-5 px-4 py-2 rounded-xl bg-accent flex gap-2"><Save size={16}/> Save AI</button></div>}
 {tab==="email"&&<div className="glass rounded-2xl p-6 mt-4 max-w-3xl"><ShieldCheck className="text-cyan"/><h2 className="font-semibold mt-4">Email configuration</h2><p className="text-sm text-slate-400 mt-2">SMTP credentials are intentionally read only from the backend `.env` file and are never exposed to the browser.</p><div className="mt-5 p-4 rounded-xl bg-white/5 text-sm">Configure SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD and EMAIL_FROM in <code>server/.env</code>.</div></div>}
 {tab==="users"&&<div className="glass rounded-2xl p-6 mt-4"><h2 className="font-semibold">Users</h2><div className="mt-5 space-y-2">{users.map(u=><div className="flex items-center justify-between p-3 rounded-xl bg-white/[.03]" key={u._id}><div><div className="text-sm">{u.name}</div><div className="text-xs text-slate-500">{u.email}</div></div><span className="text-xs px-2 py-1 rounded-lg bg-white/5">{u.role}</span></div>)}</div></div>}
 {tab==="compliance"&&<div className="glass rounded-2xl p-6 mt-4 max-w-3xl"><h2 className="font-semibold">Responsible outreach controls</h2><div className="grid md:grid-cols-3 gap-4 mt-5">{[["Hourly limit","MAX_EMAILS_PER_HOUR"],["Daily limit","MAX_EMAILS_PER_DAY"],["Campaign limit","MAX_EMAILS_PER_CAMPAIGN"]].map(x=><div className="bg-white/[.03] p-4 rounded-xl" key={x[0]}><div className="text-sm">{x[0]}</div><div className="text-xs text-slate-500 mt-1">{x[1]}</div></div>)}</div><p className="mt-5 text-sm text-slate-400">Suppression and unsubscribe records are enforced by the backend before sending.</p></div>}
 </div>
}
